### ISSUE TITLE
osmosdr never finds fosphor

### ISSUE THREAD

**Issue by 1am** [dholm/homebrew-sdr#9]
Hi 

I'm not really sure what is it caused by but whatever I try, `osmocom_fft -F` python never finds fosphor library and always crashes with the following stack:

```
# osmocom_fft -F
Mac OS; Clang version 7.0.0 (clang-700.0.72); Boost_105800; UHD_003.009.001-0-unknown

gr-osmosdr v0.1.4-48-g86ad5842 (0.1.5git) gnuradio 3.7.8
built-in source types: file fcd rtl rtl_tcp uhd hackrf rfspace 
Number of USB devices: 5
USB device 1d50:6089: 000000000000000014d463dc2f2f6de1 match
Using HackRF One with firmware 2015.07.2 
Traceback (most recent call last):
  File "/usr/local/bin/osmocom_fft", line 841, in <module>
    main ()
  File "/usr/local/bin/osmocom_fft", line 837, in main
    app = stdgui2.stdapp(app_top_block, "osmocom Spectrum Browser", nstatus=1)
  File "/usr/local/lib/python2.7/site-packages/gnuradio/wxgui/stdgui2.py", line 46, in __init__
    wx.App.__init__ (self, redirect=False)
  File "/usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gnuradio/wxgui/stdgui2.py", line 49, in OnInit
    frame = stdframe (self.top_block_maker, self.title, self._nstatus)
  File "/usr/local/lib/python2.7/site-packages/gnuradio/wxgui/stdgui2.py", line 76, in __init__
    self.panel = stdpanel (self, self, top_block_maker)
  File "/usr/local/lib/python2.7/site-packages/gnuradio/wxgui/stdgui2.py", line 98, in __init__
    self.top_block = top_block_maker (frame, self, vbox, sys.argv)
  File "/usr/local/bin/osmocom_fft", line 220, in __init__
    from gnuradio import fosphor
ImportError: cannot import name fosphor
```

I've compiled fosphor from source, also tried running cmake with `cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar` but every time it fails with the same error. I'm not necessarily sure that osmocom installed successfully because gqrx shows some signals on certain frequencies and `osmocom_fft` (without the -F flag) only shows only noise (in waterfall and plot views). I'm really struggling with this and I'm not really sure what could be wrong and I'm writing in your repo since this is the only brew formula which worked for me since gr-osmosdr.rb refers to the non-system python. Is there something obvious I'm missing to make it all work? Everything compiles, seems to work but in fact it fails in some nasty ways. I'm on OSX 10.10.5, and xCode 7.1.

**Comment by dholm** [comment]
@1am I fixed a bunch of bugs in the formulas today.  Run `brew update` and reinstall `gr-osmosdr`.

**Comment by 1am** [comment]
Hi. Thank you!

I've just trued but still fosphor seems to be missing. I've tried rebuilding and reinstalling it but nothing fixed the missing python library.

The following is the log from brew unistallation after update and uninstalling gr-osmosdr:

```
# brew install gr-osmosdr --HEAD
==> Installing gr-osmosdr from dholm/homebrew-sdr
==> Installing dependencies for dholm/sdr/gr-osmosdr: harfbuzz, soapysdr
==> Installing dholm/sdr/gr-osmosdr dependency: harfbuzz
==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-1.0.4.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring harfbuzz-1.0.4.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/harfbuzz/1.0.4: 94 files, 3.6M
==> Installing dholm/sdr/gr-osmosdr dependency: soapysdr
==> Cloning https://github.com/pothosware/SoapySDR.git
Cloning into '/Library/Caches/Homebrew/soapysdr--git'...
remote: Counting objects: 90, done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 90 (delta 2), reused 35 (delta 0), pack-reused 0
Unpacking objects: 100% (90/90), done.
Checking connectivity... done.
==> Checking out branch master
==> cmake .. -DCMAKE_SHARED_LINKER_FLAGS='-Wl,-undefined,dynamic_lookup' -DPYTHON_LIBRARY='/usr/local/lib/libgnuradio-runtime.dylib' -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FL
==> make install
🍺  /usr/local/Cellar/soapysdr/HEAD: 29 files, 1.1M, built in 22 seconds
==> Installing dholm/sdr/gr-osmosdr
==> Cloning git://git.osmocom.org/gr-osmosdr
Updating /Library/Caches/Homebrew/gr-osmosdr--git
==> Checking out branch master
==> cmake .. -DCMAKE_SHARED_LINKER_FLAGS='-Wl,-undefined,dynamic_lookup' -DPYTHON_LIBRARY='/usr/local/lib/libgnuradio-runtime.dylib' -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FL
==> make install
🍺  /usr/local/Cellar/gr-osmosdr/HEAD: 32 files, 2.5M, built in 48 seconds
```

**Comment by dholm** [comment]
@1am Looks like `gr-osmosdr` depends on `gr-fosphor`.  I just pushed an updated formula with the dependency.  Probably it's enough if you just `brew install gr-fosphor`.

**Comment by 1am** [comment]
`gr-fosphor` installs correctly but it fails to link and that's probably why it's not visible by python.

```
brew install gr-fosphor --HEAD
==> Installing gr-fosphor from dholm/homebrew-sdr
==> Cloning git://git.osmocom.org/gr-fosphor
Updating /Library/Caches/Homebrew/gr-fosphor--git
==> Checking out branch master
==> cmake .. -DCMAKE_SHARED_LINKER_FLAGS='-Wl,-undefined,dynamic_lookup' -DPYTHO
==> make install
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/gnuradio/fosphor/api.h
/usr/local/include/gnuradio/fosphor is not writable.

You can try again using:
  brew link gr-fosphor
==> Summary
🍺  /usr/local/Cellar/gr-fosphor/HEAD: 25 files, 1.0M, built in 22 seconds
```

doing a `ls /usr/local/include/gnuradio/fosphor/*` shows that the directory is empty. I think that the formula should try to link against ls `/usr/local/Cellar/gr-fosphor/HEAD/include/gnuradio/fosphor/` ?

**Comment by dholm** [comment]
Hmm, run `ls -l /usr/local/include/gnuradio/fosphor` and check the permissions.  It says the path is not writable so the permissions might be incorrect.

You can try `sudo chmod $(whoami):admin /usr/local/include/gnuradio/fosphor` followed by `brew link gr-fosphor`.

**Comment by 1am** [comment]
Great! Thank you, works like a charm :)
For reference I had to do:

```
sudo chown -R $(whoami):admin /usr/local/include/gnuradio/fosphor
brew link gr-fosphor
```

and after that I needed to install OpenGL for python via:

```
pip install PyOpenGL PyOpenGL_accelerate
```
